/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_jna_Pointer */

#ifndef _Included_com_sun_jna_Pointer
#define _Included_com_sun_jna_Pointer
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: SIZE */
/* Inaccessible static: BOOL_SIZE */
/* Inaccessible static: NULL */
/* Inaccessible static: class_00024com_00024sun_00024java_00024jnidispatch_00024NativePointer */
/*
 * Class:     com_sun_jna_Pointer
 * Method:    write
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_write__I_3BII
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    write
 * Signature: (I[SII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_write__I_3SII
  (JNIEnv *, jobject, jint, jshortArray, jint, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    write
 * Signature: (I[CII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_write__I_3CII
  (JNIEnv *, jobject, jint, jcharArray, jint, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    write
 * Signature: (I[III)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_write__I_3III
  (JNIEnv *, jobject, jint, jintArray, jint, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    write
 * Signature: (I[JII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_write__I_3JII
  (JNIEnv *, jobject, jint, jlongArray, jint, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    write
 * Signature: (I[FII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_write__I_3FII
  (JNIEnv *, jobject, jint, jfloatArray, jint, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    write
 * Signature: (I[DII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_write__I_3DII
  (JNIEnv *, jobject, jint, jdoubleArray, jint, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    read
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_read__I_3BII
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    read
 * Signature: (I[SII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_read__I_3SII
  (JNIEnv *, jobject, jint, jshortArray, jint, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    read
 * Signature: (I[CII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_read__I_3CII
  (JNIEnv *, jobject, jint, jcharArray, jint, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    read
 * Signature: (I[III)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_read__I_3III
  (JNIEnv *, jobject, jint, jintArray, jint, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    read
 * Signature: (I[JII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_read__I_3JII
  (JNIEnv *, jobject, jint, jlongArray, jint, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    read
 * Signature: (I[FII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_read__I_3FII
  (JNIEnv *, jobject, jint, jfloatArray, jint, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    read
 * Signature: (I[DII)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_read__I_3DII
  (JNIEnv *, jobject, jint, jdoubleArray, jint, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    getByte
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_com_sun_jna_Pointer_getByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    getShort
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_com_sun_jna_Pointer_getShort
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    getInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_sun_jna_Pointer_getInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    getLong
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jna_Pointer_getLong
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    getFloat
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_sun_jna_Pointer_getFloat
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    getDouble
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_sun_jna_Pointer_getDouble
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    getPointer
 * Signature: (I)Lcom/sun/java/jnidispatch/NativePointer;
 */
JNIEXPORT jobject JNICALL Java_com_sun_jna_Pointer_getPointer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    getString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_jna_Pointer_getString
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    setByte
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_setByte
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    setShort
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_setShort
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    setInt
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_setInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    setLong
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_setLong
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    setFloat
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_setFloat
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    setDouble
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_setDouble
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    setPointer
 * Signature: (ILcom/sun/java/jnidispatch/NativePointer;)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_setPointer
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    setString
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Pointer_setString
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    initIDs
 * Signature: (Lcom/sun/java/jnidispatch/NativePointer;)I
 */
JNIEXPORT jint JNICALL Java_com_sun_jna_Pointer_initIDs
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_sun_jna_Pointer
 * Method:    getBoolSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_jna_Pointer_getBoolSize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
