/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_jna_Memory */

#ifndef _Included_com_sun_jna_Memory
#define _Included_com_sun_jna_Memory
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: SIZE */
/* Inaccessible static: BOOL_SIZE */
/* Inaccessible static: NULL */
/* Inaccessible static: class_00024com_00024sun_00024java_00024jnidispatch_00024NativePointer */
/*
 * Class:     com_sun_jna_Memory
 * Method:    malloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jna_Memory_malloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sun_jna_Memory
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Memory_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
