/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_jna_Function */

#ifndef _Included_com_sun_jna_Function
#define _Included_com_sun_jna_Function
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: SIZE */
/* Inaccessible static: BOOL_SIZE */
/* Inaccessible static: NULL */
/* Inaccessible static: class_00024com_00024sun_00024java_00024jnidispatch_00024NativePointer */
#undef com_sun_jna_Function_C_CONVENTION
#define com_sun_jna_Function_C_CONVENTION 0L
#undef com_sun_jna_Function_STDCALL_CONVENTION
#define com_sun_jna_Function_STDCALL_CONVENTION 1L
/* Inaccessible static: NO_ARGS */
/*
 * Class:     com_sun_jna_Function
 * Method:    invokeInt
 * Signature: (I[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_sun_jna_Function_invokeInt
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     com_sun_jna_Function
 * Method:    invokeVoid
 * Signature: (I[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_sun_jna_Function_invokeVoid
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     com_sun_jna_Function
 * Method:    invokeFloat
 * Signature: (I[Ljava/lang/Object;)F
 */
JNIEXPORT jfloat JNICALL Java_com_sun_jna_Function_invokeFloat
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     com_sun_jna_Function
 * Method:    invokeDouble
 * Signature: (I[Ljava/lang/Object;)D
 */
JNIEXPORT jdouble JNICALL Java_com_sun_jna_Function_invokeDouble
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     com_sun_jna_Function
 * Method:    invokePointer
 * Signature: (I[Ljava/lang/Object;)Lcom/sun/java/jnidispatch/NativePointer;
 */
JNIEXPORT jobject JNICALL Java_com_sun_jna_Function_invokePointer
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     com_sun_jna_Function
 * Method:    find
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_jna_Function_find
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
