package com.sun.jna.platform.win32.structures;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.platform.win32.WinDef;

/**
 * Contains information about a simulated message generated by an input device other than a keyboard or mouse.
 */
public class HARDWAREINPUT extends Structure {

    public static class ByReference extends HARDWAREINPUT implements Structure.ByReference {
        public ByReference() {
        }

        public ByReference(Pointer memory) {
            super(memory);
        }
    }

    public HARDWAREINPUT() {
        setAlignType(Structure.ALIGN_MSVC);
    }

    public HARDWAREINPUT(Pointer memory) {
        setAlignType(Structure.ALIGN_MSVC);
        useMemory(memory);
        read();
    }

    public WinDef.DWORD uMsg;
    public WinDef.WORD wParamL;
    public WinDef.WORD wParamH;
}